name: MSBuild

on: [push]
    
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - run: |
          msbuild -r PoshWinRT/PoshWinRT.csproj
